version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  telegram:
    build: ./telegram
    ports:
      - 5000:5000

  backend:
    build: ./backend
    ports:
      - 8080:8080
    links:
      - mongo

  nginx:
    build: ./nginx
    ports:
      - 443:443
    depends_on:
      - frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
      - ./frontend:/usr/share/nginx/html
    environment:
      - NGINX_HOST=d-art.space
      - NGINX_PORT=80
      - NGINX_SSL_PORT=443

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example